Fixed issue with cheerio types.
mwpenny/kijiji-scraper pull request #45
Opened 2020-12-11 19:41 UTC by technoligest

2020-12-11 23:06 UTC, mwpenny requested changes
Thanks for the quick fix! I just have a few comments.

2020-12-11 23:06 UTC, mwpenny commented on lib/backends/api-scraper.ts
> +    return (element as cheerio.TagElement).attribs !== undefined;
There's an easier way to check this that I think is cleaner:

```ts
element.type === "tag";
```

2020-12-11 23:06 UTC, mwpenny commented on lib/backends/api-scraper.ts
> +        return false;
The intent behind this function is to return the original value if it can't be parsed. Can you move

```ts
value = value.trim();
```

to the top of this function and just return `value` instead of `false` here?

2020-12-11 23:06 UTC, mwpenny commented on lib/backends/api-scraper.ts
> +        if  (!isCheerioTagElement(item)) {
Style: only one space after `if` please.

2020-12-11 23:06 UTC, mwpenny commented on lib/backends/api-scraper.ts
> +        if  (!isCheerioTagElement(item)) {
Style: only one space after `if` please.

2020-12-11 23:06 UTC, mwpenny commented on package.json
> +    "typescript": "^4.1.2"
User-defined type guards aren't a new feature, so there's no need to update the TypeScript version. That's a decision I think requires more thought.

2020-12-11 23:06 UTC, mwpenny commented on package.json
> +    "typescript": "^4.1.2"
Also, please update the version of `@types/cheerio` to explicitly use the latest (0.22.23).

2020-12-12 05:57 UTC, mwpenny requested changes
Just a few small things regarding your `isCheerioTagElement()` changes (see my comment).

Also, please don't commit `package-lock.json`. `kijiji-scraper` is a library, which means end-users don't consume it directly and `package-lock.json` will be ignored for them. In other words, it prevents upstream breaking changes from impacting _us_, but does nothing to prevent issues for users.

Checking it in therefore provides a false sense of security and could potentially allow breaking changes in dependencies to slip through the cracks when testing. So I would rather omit the file and test what users will actually receive when the library is installed. If there's a problem, I want the build break so that we're aware sooner, rather than masking the problem.

If this were an application and not a library, then a lockfile would make sense since it would actually protect users from breaking changes in dependencies.

2020-12-12 05:57 UTC, mwpenny commented on lib/backends/api-scraper.ts
> +    return element.type !== 'text';
Right now there are only 2 Cheerio element types (text and tag), but we don't know if that will change in the future. Rather than checking what it's _not_, you should check what it _is_. I.e., `element.type === "tag"`. Also, please use double quotes for consistency with the rest of the library.

2020-12-14 02:52 UTC, technoligest commented on lib/backends/api-scraper.ts
> +    return element.type !== 'text';
LMAO Really sorry, made the change while in a meeting will push the fix in a min

2020-12-14 17:35 UTC, merged