Expose more and better ad images
mwpenny/kijiji-scraper pull request #5
Opened 2017-01-10 22:44 UTC by MrDOS

The listing image gallery is trivially accessible to the parser. This pull request makes the images available to the user via another property on the ad, `images`. Some attempt is made to provide the consumer with higher-resolution images than the Kijiji web interface would have you know exists.

(Two PRs in the same day – if you want me to shut up, that's fine...)

2017-01-10 23:30 UTC, mwpenny requested changes
Working on a cool project eh? ;p

My original use-case for this library was a chat bot. This feature would be good for more graphical apps. One very small change to the readme

2017-01-10 23:30 UTC, mwpenny commented on README.md
> +The image URL given in `image` is featured image for the ad and will be up to
Small typo: The image URL given in `image` is _the_ featured image for the ad

2017-01-11 00:41 UTC, MrDOS commented on README.md
> +The image URL given in `image` is featured image for the ad and will be up to
Whoops, good catch.

2017-01-11 00:54 UTC, MrDOS commented
There, all better now.

I'm trying to filter/rank listings based on scores generated by heuristic functions. My immediate application is apartment hunting: “how close is the listing price to $n”, “how close is the listing to location Y, X”, etc. instead of simply “well, it's got ‘Greenboro’ in the description somewhere”. Not to mention you practically need NLP to figure out if parking is included or not. Images aren't required for the actual data collection and calculation (computer vision to judge cleanliness is a little outside of the project scope) but it's nice to have URLs ready to go to feed into the frontend.

2017-01-11 01:31 UTC, mwpenny commented
Looks good!

Haha I made this for apartment hunting as well. You might want to look at properties for the `params` object for refining your search. They are undocumented and can be found by inspecting POST requests made when performing custom searches on the actual Kijiji website.

For example, `minPrice` and `maxPrice` can be used to set your price range, and `address` and `radius` can be used to set the starting location (either actual address or the postal code) and refine the search radius (in kilometers). There are some other fields for number of bedrooms, etc that I can't recall. I assume Kijiji sorts the returned results based on these criteria but this needs to be confirmed.

2017-01-11 01:31 UTC, mwpenny approved these changes

2017-01-11 01:31 UTC, merged

2017-01-11 01:36 UTC, MrDOS commented
> You might want to look at properties for the `params` object for refining your search.

Yeah I saw that and some of those options. My current plan is to dumbly scrape everything that pops up on the top-level category feed and cache it so I can reshape criteria at will, but Kijiji's filtering might be useful for absolute bounding.